name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Build Wasabi
        run: make build
      - name: Upload Wasabi
        uses: actions/upload-artifact@main
        with:
          name: WasabiOS
          path: mnt

